name: mec-events-app
region: sfo3

services:
  - name: backend
    github:
      repo: carloschuck/Mec-events
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    
    routes:
      - path: /api
        preserve_path_prefix: true
    
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        value: lNng1n0bCJhd9HjvkNWvXp05HVQJTN+YC+gD3PcyIKI=
        type: SECRET
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: WEBHOOK_SECRET
        value: juzl3DuBkbGej3c7+BTWVKdQIydUJuVZJrMld4GlZac=
        type: SECRET
      - key: DEFAULT_SOURCE_URL
        value: https://housesoflight.org
      - key: MEC_API_URL
        value: https://housesoflight.org/wp-json/mec/v1.0
      - key: CLIENT_URL
        value: ${APP_URL}
      - key: ORG_NAME
        value: Houses of Light
      - key: SYNC_CRON_SCHEDULE
        value: "0 */3 * * *"
      - key: REMINDER_CRON_SCHEDULE
        value: "0 9 * * *"
      # Database connection (external managed database)
      - key: DB_HOST
        value: mec-events-db-do-user-24283710-0.m.db.ondigitalocean.com
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: doadmin
      - key: DB_PASSWORD
        value: YOUR_DATABASE_PASSWORD_HERE
        type: SECRET
      - key: DB_SKIP_SYNC
        value: "true"
        scope: RUN_AND_BUILD_TIME

  - name: frontend
    github:
      repo: carloschuck/Mec-events
      branch: main
      deploy_on_push: true
    source_dir: frontend
    dockerfile_path: frontend/Dockerfile
    
    routes:
      - path: /
    
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    
    envs:
      - key: VITE_API_URL
        value: ${APP_URL}/api
        scope: RUN_AND_BUILD_TIME

# Using external managed database
# Database: mec-events-db (PostgreSQL 15, SFO3)
# Host: mec-events-db-do-user-24283710-0.m.db.ondigitalocean.com
